spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_security_model
        username: root
        password: djr13232319788

    data:
        redis:
            database: 0
            host: 127.0.0.1
            port: 6379
            password: djr13232319788
            jedis:
                pool:
                    max-wait: 2000ms
                    min-idle: 2
                    max-idle: 8
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    mapper-locations: classpath*:mapper/*.xml